# Numpy

In [74]:
import numpy as np
np.__version__ #to check version

'1.19.5'

# Creation of Array

In [75]:
arr1=np.array([3,4,6,8,7]) #list convert to arry
arr1,   type(arr1)   #nd---> n diamontioal

(array([3, 4, 6, 8, 7]), numpy.ndarray)

In [5]:
arr1=np.array((3,4,6,8,7)) #touple convert to arry
arr1,type(arr1)   #nd---> n diamontioal

(array([3, 4, 6, 8, 7]), numpy.ndarray)

In [6]:
arr2=np.arange(5,12) #range in array
arr2

array([ 5,  6,  7,  8,  9, 10, 11])

In [7]:
arr2=np.arange(5,12,2)  #range in array
arr2

array([ 5,  7,  9, 11])

In [76]:
arr3=np.linspace(2,5,1000)  #linspace---> 2 theke 5 er moddhe kto gulo sample chai. means 2 theke 5 er moddhe kto gulo number+ hidden  number ase ta show korbe and 1000---> ta number
arr3

array([2.        , 2.003003  , 2.00600601, 2.00900901, 2.01201201,
       2.01501502, 2.01801802, 2.02102102, 2.02402402, 2.02702703,
       2.03003003, 2.03303303, 2.03603604, 2.03903904, 2.04204204,
       2.04504505, 2.04804805, 2.05105105, 2.05405405, 2.05705706,
       2.06006006, 2.06306306, 2.06606607, 2.06906907, 2.07207207,
       2.07507508, 2.07807808, 2.08108108, 2.08408408, 2.08708709,
       2.09009009, 2.09309309, 2.0960961 , 2.0990991 , 2.1021021 ,
       2.10510511, 2.10810811, 2.11111111, 2.11411411, 2.11711712,
       2.12012012, 2.12312312, 2.12612613, 2.12912913, 2.13213213,
       2.13513514, 2.13813814, 2.14114114, 2.14414414, 2.14714715,
       2.15015015, 2.15315315, 2.15615616, 2.15915916, 2.16216216,
       2.16516517, 2.16816817, 2.17117117, 2.17417417, 2.17717718,
       2.18018018, 2.18318318, 2.18618619, 2.18918919, 2.19219219,
       2.1951952 , 2.1981982 , 2.2012012 , 2.2042042 , 2.20720721,
       2.21021021, 2.21321321, 2.21621622, 2.21921922, 2.22222

In [9]:
np.random.random(10)  #random array inisilize kore./10 values

array([0.93396509, 0.99840265, 0.48041678, 0.68972013, 0.00318397,
       0.92152124, 0.84946199, 0.91832137, 0.70996146, 0.72613661])

# Generation

In [77]:
#need 2 dim array
arr5=np.empty([2,2]) #we get some random values by 2*2 matrix and it`s give random numbers.
arr5

array([[ 0.        , 15.65247584],
       [31.30495168, 46.95742753]])

In [78]:
#need 2 dim array
arr5=np.empty([2,3]) #we get some random values by 2*3 matrix and it`s give random numbers.
arr5

array([[2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [12]:
arr1.ndim #ndim---->check dimension.

1

In [13]:
arr1

array([3, 4, 6, 8, 7])

In [79]:
arr1.size

5

In [15]:
arr1.shape ,  arr5.shape

((5,), (2, 3))

In [16]:
arr1.dtype

dtype('int32')

In [17]:
#need 2 dim array
arr5=np.empty([2,3],dtype=np.int64) #we get some random values by 2*3 matrix
arr5

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [18]:
arr5.dtype

dtype('int64')

In [19]:
arr1.itemsize #it contain 4 bite address

4

In [20]:
arr5.itemsize  #it contain 8 bite of space

8

# Identy Matrix

In [81]:
np.eye(3,3) #nijer position sudhu 1 hbe bki gulo 0 hbe

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.eye(3,3, k=1) #1 dile samne 0 hbe,columns wise 

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
np.eye(3,3, k=-1) #-1 dile samne 0 hbe,row wise 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [24]:
np.zeros([2,2])   #matrix with 0`s

array([[0., 0.],
       [0., 0.]])

In [25]:
np.ones([3,3])   #matrix with 1`s

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full((3,3), 9) #3*3 matrix fill with 9

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

# Array types

In [27]:
#int arary
intArray=np.array([5,6,7],dtype=np.int64)
intArray

array([5, 6, 7], dtype=int64)

In [28]:
#int arary
flotArray=np.array([5,6,7],dtype=np.float64)
flotArray

array([5., 6., 7.])

In [82]:
#complex array
comArray=np.array([5,6,7],dtype=np.complex64)
comArray,  comArray.imag #----> just give me imaganary number

(array([5.+0.j, 6.+0.j, 7.+0.j], dtype=complex64),
 array([0., 0., 0.], dtype=float32))

In [30]:
#String array
stringArray=np.array(["Apple","ball","cat"], dtype=np.string_)
stringArray  #b--->byte from

array([b'Apple', b'ball', b'cat'], dtype='|S5')

In [31]:
#bool arary
intarray=np.array([5,6,7,0],dtype=np.bool8)
intarray

array([ True,  True,  True, False])

In [32]:
def f(r,c):
    return r*c #r*c is the indices
arr7=np.fromfunction(f, shape=(4,4)) #eta 3*3 matrix dicce /r*c=row & columns
arr7

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

# slicing

In [33]:
arr7[1:, 1:]

array([[1., 2., 3.],
       [2., 4., 6.],
       [3., 6., 9.]])

In [34]:
arr7[1::2]

array([[0., 1., 2., 3.],
       [0., 3., 6., 9.]])

# Filtering

In [35]:
arr7[arr7 > 2] #we  get getter then 2 values

array([3., 4., 6., 3., 6., 9.])

In [36]:
arr7[(arr7 > 2) & (arr7 <9)] #we  get getter then 2  and small then 9values

array([3., 4., 6., 3., 6.])

In [37]:
arr7[~(arr7<2)] #~ ----> True chara bki gulo share korbe mane 2 er theke bro gulo bad e sob pbo

array([2., 3., 2., 4., 6., 3., 6., 9.])

In [38]:
arr7>2

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False,  True,  True],
       [False,  True,  True,  True]])

# Scaler Operation

In [39]:
arr8=np.arange(4,10)
arr8

array([4, 5, 6, 7, 8, 9])

In [40]:
arr8+2,arr8-2,arr8*2,arr8/2

(array([ 6,  7,  8,  9, 10, 11]),
 array([2, 3, 4, 5, 6, 7]),
 array([ 8, 10, 12, 14, 16, 18]),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5]))

In [41]:
arr8**2,  arr8%2

(array([16, 25, 36, 49, 64, 81], dtype=int32),
 array([0, 1, 0, 1, 0, 1], dtype=int32))

In [42]:
np.add(arr8,2),np.subtract(arr8,2),np.multiply(arr8,2),np.divide(arr8,2),np.power(arr8,2),np.mod(arr8,2)

(array([ 6,  7,  8,  9, 10, 11]),
 array([2, 3, 4, 5, 6, 7]),
 array([ 8, 10, 12, 14, 16, 18]),
 array([2. , 2.5, 3. , 3.5, 4. , 4.5]),
 array([16, 25, 36, 49, 64, 81], dtype=int32),
 array([0, 1, 0, 1, 0, 1], dtype=int32))

# Matrix and Vector OPeration 

In [43]:
arr8+arr8

array([ 8, 10, 12, 14, 16, 18])

In [44]:
arr8

array([4, 5, 6, 7, 8, 9])

In [45]:
arr8**arr8

array([      256,      3125,     46656,    823543,  16777216, 387420489],
      dtype=int32)

# Matrix Multipication

In [46]:
#columns of first == rows of 2nd matrix and we use @ for multipication
arr8=arr7@arr7

# Stastics

In [47]:
arr7

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [48]:
arr8.mean()   # return whole Matrix mean

31.5

In [49]:
arr8.mean(axis=0)   # mean of rows

array([ 0., 21., 42., 63.])

In [50]:
arr8.mean(axis=1)   # mean of columns

array([ 0., 21., 42., 63.])

In [51]:
# Median
np.median(arr8), np.median(arr8, axis=0), np.median(arr8, axis=1)

(21.0, array([ 0., 21., 42., 63.]), array([ 0., 21., 42., 63.]))

In [52]:
arr8.any(), arr8.all() #any---> any value true ki na check korbe/ all--> all value true hole true return korbe

(True, False)

In [53]:
# Variance
arr8.var(), arr8.var(axis=0), arr8.var(axis=1)

(1408.75,
 array([   0.,  245.,  980., 2205.]),
 array([   0.,  245.,  980., 2205.]))

In [54]:
arr8.min(), arr8.max()

(0.0, 126.0)

In [55]:
arr8.min(axis=0), arr8.max(axis=0)

(array([0., 0., 0., 0.]), array([  0.,  42.,  84., 126.]))

In [56]:
# Standard Deviation
np.std(arr8, axis=0)

array([ 0.        , 15.65247584, 31.30495168, 46.95742753])

# Shaping


In [57]:
X = np.linspace(1,10, 12)
Y = np.linspace(11,20, 12)
X,Y

(array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
         5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
         9.18181818, 10.        ]),
 array([11.        , 11.81818182, 12.63636364, 13.45454545, 14.27272727,
        15.09090909, 15.90909091, 16.72727273, 17.54545455, 18.36363636,
        19.18181818, 20.        ]))

In [58]:
X = np.linspace(1,10, 12)
X, X.shape

(array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
         5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
         9.18181818, 10.        ]),
 (12,))

In [59]:
X = np.linspace(1,10, 12)
X, X.shape

(array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
         5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
         9.18181818, 10.        ]),
 (12,))

In [83]:
# Reshaping/ change the shape = 3 rows 4 columns/value size same hote hbe/(3,4)---reshape-->(4,3)
X.reshape(4,3)

array([[ 1.        ,  1.81818182,  2.63636364],
       [ 3.45454545,  4.27272727,  5.09090909],
       [ 5.90909091,  6.72727273,  7.54545455],
       [ 8.36363636,  9.18181818, 10.        ]])

In [61]:
X.reshape(-1,1)

array([[ 1.        ],
       [ 1.81818182],
       [ 2.63636364],
       [ 3.45454545],
       [ 4.27272727],
       [ 5.09090909],
       [ 5.90909091],
       [ 6.72727273],
       [ 7.54545455],
       [ 8.36363636],
       [ 9.18181818],
       [10.        ]])

In [62]:
# into 1D
arr8.ravel(),arr8.shape

(array([  0.,   0.,   0.,   0.,   0.,  14.,  28.,  42.,   0.,  28.,  56.,
         84.,   0.,  42.,  84., 126.]),
 (4, 4))

In [63]:
X.reshape(-1,1) #columns gulo ke rows korbe

array([[ 1.        ],
       [ 1.81818182],
       [ 2.63636364],
       [ 3.45454545],
       [ 4.27272727],
       [ 5.09090909],
       [ 5.90909091],
       [ 6.72727273],
       [ 7.54545455],
       [ 8.36363636],
       [ 9.18181818],
       [10.        ]])

In [64]:
X.reshape(-1,1)

array([[ 1.        ],
       [ 1.81818182],
       [ 2.63636364],
       [ 3.45454545],
       [ 4.27272727],
       [ 5.09090909],
       [ 5.90909091],
       [ 6.72727273],
       [ 7.54545455],
       [ 8.36363636],
       [ 9.18181818],
       [10.        ]])

In [65]:
X.reshape(1,-1)

array([[ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
         5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
         9.18181818, 10.        ]])

In [66]:
arr8

array([[  0.,   0.,   0.,   0.],
       [  0.,  14.,  28.,  42.],
       [  0.,  28.,  56.,  84.],
       [  0.,  42.,  84., 126.]])

In [67]:
# into 1D
arr8.ravel()

array([  0.,   0.,   0.,   0.,   0.,  14.,  28.,  42.,   0.,  28.,  56.,
        84.,   0.,  42.,  84., 126.])

In [68]:
arr8.flatten()  # into 1D

array([  0.,   0.,   0.,   0.,   0.,  14.,  28.,  42.,   0.,  28.,  56.,
        84.,   0.,  42.,  84., 126.])

In [69]:
arr9 = np.array([
    [2,3],
    [41,5],
    [7,8]
])

In [70]:
arr9

array([[ 2,  3],
       [41,  5],
       [ 7,  8]])

In [71]:
arr9.T      # Transposing MAtrix

array([[ 2, 41,  7],
       [ 3,  5,  8]])

In [72]:
arr9.transpose()  # Transposing MAtrix

array([[ 2, 41,  7],
       [ 3,  5,  8]])

In [73]:
arr9.argmin(axis=1), arr9.argmax() #argmin/argmax-->index return korbe

(array([0, 1, 0], dtype=int64), 2)